name: Workflow run

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - dev
      - main

jobs:
  setup_deploy_params:
    runs-on: ubuntu-latest
    steps:
      - name: if dev
        if: ${{ github.event.workflow_run.head_branch != 'dev' }}
        run: echo "dev!!"
      - name: if main
        if: ${{ github.event.workflow_run.head_branch != 'main' }}
        run: echo "main!!"
